/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aula07;

import ferramentas.Globais;
import modelos.Questionario;

/**
 *
 * @author maaschmidt
 */
public class TelaQuestionario extends javax.swing.JFrame {

    /**
     * Creates new form questionario
     */
    Questionario[] vetorQuestoes = new Questionario[3];
    int count = -1, acerto = 0;

    public TelaQuestionario() {
        initComponents();

        Questionario objQuestao = new Questionario();
        objQuestao.setPergunta("QUESTÃO 1: \n9! = ?");
        objQuestao.setRespostaA("9");
        objQuestao.setRespostaB("362.880");
        objQuestao.setRespostaC("362.280");
        objQuestao.setRespostaCorreta('B');
        vetorQuestoes[0] = objQuestao;

        Questionario objQuestao2 = new Questionario();
        objQuestao2.setPergunta("QUESTÃO 2: \n5 + (2 * 10) - 15  = ?");
        objQuestao2.setRespostaA("10");
        objQuestao2.setRespostaB("55");
        objQuestao2.setRespostaC("30");
        objQuestao2.setRespostaCorreta('A');
        vetorQuestoes[1] = objQuestao2;

        Questionario objQuestao3 = new Questionario();
        objQuestao3.setPergunta("QUESTÃO 3: \n5 + 2 * 10 - 15 = ?");
        objQuestao3.setRespostaA("55");
        objQuestao3.setRespostaB("30");
        objQuestao3.setRespostaC("10");
        objQuestao3.setRespostaCorreta('C');
        vetorQuestoes[2] = objQuestao3;

        fazerPergunta();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        btnSair = new javax.swing.JButton();
        lblPergunta = new javax.swing.JLabel();
        rbtAlternativaA = new javax.swing.JRadioButton();
        rbtAlternativaB = new javax.swing.JRadioButton();
        rbtAlternativaC = new javax.swing.JRadioButton();
        lblMensagem = new javax.swing.JLabel();
        lblFooterSpace = new javax.swing.JLabel();
        lblAcertos = new javax.swing.JLabel();
        btnAvancar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Fira Code Light", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("QUESTIONÁRIO");
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 68));

        btnSair.setBackground(new java.awt.Color(60, 63, 65));
        btnSair.setText("SAIR");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        getContentPane().add(btnSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, 70, 20));

        lblPergunta.setText("Qual a pergunta?");
        getContentPane().add(lblPergunta, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 86, -1, -1));

        buttonGroup1.add(rbtAlternativaA);
        rbtAlternativaA.setText("jRadioButton1");
        getContentPane().add(rbtAlternativaA, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 122, -1, -1));

        buttonGroup1.add(rbtAlternativaB);
        rbtAlternativaB.setText("jRadioButton2");
        getContentPane().add(rbtAlternativaB, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 156, -1, -1));

        buttonGroup1.add(rbtAlternativaC);
        rbtAlternativaC.setText("jRadioButton3");
        getContentPane().add(rbtAlternativaC, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 190, -1, -1));

        lblMensagem.setFont(new java.awt.Font("DejaVu Sans", 0, 15)); // NOI18N
        lblMensagem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lblMensagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 400, -1));
        getContentPane().add(lblFooterSpace, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, -1, 20));
        getContentPane().add(lblAcertos, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 140, 20));

        btnAvancar1.setText("AVANÇAR");
        btnAvancar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvancar1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnAvancar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 252, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnAvancar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvancar1ActionPerformed
        if (rbtAlternativaA.isSelected() || rbtAlternativaB.isSelected() || rbtAlternativaC.isSelected()) {
            if (rbtAlternativaA.isSelected() && vetorQuestoes[count].getRespostaCorreta() == 'A') {
                Globais.exibirMensagem("Acertou");
                acerto++;
            } else if (rbtAlternativaB.isSelected() && vetorQuestoes[count].getRespostaCorreta() == 'B') {
                Globais.exibirMensagem("Acertou");
                acerto++;
            } else if (rbtAlternativaC.isSelected() && vetorQuestoes[count].getRespostaCorreta() == 'C') {
                Globais.exibirMensagem("Acertou");
                acerto++;
            } else {
                Globais.exibirMensagem("Errou");
            }
            fazerPergunta();
        } else {
            Globais.exibirMensagem("Escolha uma alternativa");
        }
    }//GEN-LAST:event_btnAvancar1ActionPerformed

    private void fazerPergunta() {
        count++;
        buttonGroup1.clearSelection();
        if (count < vetorQuestoes.length) {
            lblPergunta.setText(vetorQuestoes[count].getPergunta());
            rbtAlternativaA.setText(vetorQuestoes[count].getRespostaA());
            rbtAlternativaB.setText(vetorQuestoes[count].getRespostaB());
            rbtAlternativaC.setText(vetorQuestoes[count].getRespostaC());
        }else {
            lblAcertos.setText("Acertos: " + acerto);
        }
            
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaQuestionario.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaQuestionario.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaQuestionario.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaQuestionario.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaQuestionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvancar1;
    private javax.swing.JButton btnSair;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAcertos;
    private javax.swing.JLabel lblFooterSpace;
    private javax.swing.JLabel lblMensagem;
    private javax.swing.JLabel lblPergunta;
    private javax.swing.JRadioButton rbtAlternativaA;
    private javax.swing.JRadioButton rbtAlternativaB;
    private javax.swing.JRadioButton rbtAlternativaC;
    // End of variables declaration//GEN-END:variables
}
